routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

/****** ADMIN *******/

Route::prefix('igc-admin')->group(function () {
    Route::get('login', 'Admin\AuthController@showLoginForm')->name('admin.loginForm');
    Route::post('login', 'Admin\AuthController@login')->name('admin.login');
    Route::post('logout', 'Admin\AuthController@logout')->name('admin.logout');

    Route::group(['middleware' => 'admin.auth'], function() {
        Route::get('pages', 'Admin\PageController@index')->name('admin.pages.index');
        Route::get('pages/create', 'Admin\PageController@create')->name('admin.pages.create');
        Route::post('pages', 'Admin\PageController@store')->name('admin.pages.store');
        Route::get('pages/{id}', 'Admin\PageController@edit')->name('admin.pages.edit');
        Route::put('pages/{id}', 'Admin\PageController@update')->name('admin.pages.update');
        Route::delete('pages/{id}', 'Admin\PageController@destroy')->name('admin.pages.destroy');
        Route::resource('categories', 'Admin\CategoryController')->except(['show']);
        Route::resource('cities', 'Admin\CityController')->except(['show']);
        Route::resource('advertisements', 'Admin\AdvertisementController')->except(['show']);
        Route::delete('advertisements/{advertisement}/image/{image}', 'Admin\AdvertisementController@deleteImage');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/advertisements/{advertisement}', 'HomeController@show')->name('showAdvertisement');

app/Advertisement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Advertisement extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'price',
        'active',
        'expires_at',
        'views_count'
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    protected $dates = ['expires_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {
        return $this->hasMany(AdvertisementImage::class)->orderBy('id', 'DESC');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class, 'advertisement_categories');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function cities()
    {
        return $this->belongsToMany(City::class, 'advertisement_cities');
    }

    /**
     * @param $nameInput
     */
    public function attachCategories($nameInput)
    {
        if (count($nameInput) > 0) {
            foreach ($nameInput as $value) {
                $this->categories()->attach($value, ['advertisement_id' => $this->id]);
            }
        }
    }

    /**
     * @param $nameInput
     */
    public function attachCities($nameInput)
    {
        if (count($nameInput) > 0) {
            foreach ($nameInput as $value) {
                $this->cities()->attach($value, ['advertisement_id' => $this->id]);
            }
        }
    }

    /**
     * @return mixed
     */
    public static function getActiveAds()
    {
        return self::where('active', true)->orderBy('created_at', 'DESC')->get();
    }
}

app/Http/Controllers/Admin/AdvertisementController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Advertisement;
use App\AdvertisementImage;
use App\City;
use App\Category;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class AdvertisementController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $ads = Advertisement::orderBy('id', 'DESC')->get();
        return view('admin.advertisements.index', compact('ads'));
    }

    /**
     * Show the form for creating a new page.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = City::orderBy('title', 'ASC')->get();
        $categories = Category::orderBy('title', 'ASC')->get();
        return view('admin.advertisements.create', compact('cities', 'categories'));
    }

    /**
     * Store new page
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validateRequest($request);

        $ad = Advertisement::create([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'price' => $request->get('price'),
            'active' => $request->get('active'),
            'expires_at' => Carbon::createFromFormat('Y-m-d', $request->get('expires_at'), 'Europe/Sofia')
        ]);

        if ($request->hasFile('main_filename')) {
            Storage::disk('uploads')->putFileAs('uploads/advertisements/' . $ad->id, $request->file('main_filename'), $request->file('main_filename')->getClientOriginalName());
            $ad->images()->create([
                'filename' => $request->file('main_filename')->getClientOriginalName(),
                'main_filename' => true
            ]);
        }

        if ($request->file('images') && count($request->file('images')) > 0) {
            foreach ($request->file('images') as $key => $file) {
                $uploadedFile = $request->file('images.' . $key . '.filename');
                Storage::disk('uploads')->putFileAs('uploads/advertisements/' . $ad->id, $uploadedFile, $uploadedFile->getClientOriginalName());
                $ad->images()->create([
                    'filename' => $uploadedFile->getClientOriginalName(),
                    'main_filename' => false
                ]);
            }
        }

        $ad->attachCategories($request->get('categories'));
        $ad->attachCities($request->get('cities'));

        return redirect()->route('advertisements.edit', ['advertisement' => $ad->id]);
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        try {
            $ad = Advertisement::findOrFail($id);
        } catch (ModelNotFoundException $exception) {
            return redirect()->route('advertisements.index')->withErrors($exception);
        }

        $cities = City::orderBy('title', 'ASC')->get();
        $categories = Category::orderBy('title', 'ASC')->get();
        $adMainImage = $ad->images()->where('main_filename', true)->first();
        $adImages = $ad->images()->where('main_filename', false)->get();

        return view('admin.advertisements.edit', compact('ad', 'cities', 'categories', 'adMainImage', 'adImages'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            $ad = Advertisement::findOrFail($id);
        } catch (ModelNotFoundException $exception) {
            return redirect()->route('advertisements.index')->withErrors($exception);
        }

        $this->validateRequest($request, $id);

        $ad->update([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'price' => $request->get('price'),
            'active' => $request->get('active'),
            'expires_at' => Carbon::createFromFormat('Y-m-d', $request->get('expires_at'), 'Europe/Sofia')
        ]);

        if ($request->hasFile('main_filename')) {
            $adMainImage = $ad->images()->where('main_filename', true)->first();
            Storage::disk('uploads')->delete('uploads/advertisements/' . $ad->id . '/' . $adMainImage->filename);
            Storage::disk('uploads')->putFileAs('uploads/advertisements/' . $ad->id, $request->file('main_filename'), $request->file('main_filename')->getClientOriginalName());
            $adMainImage->update([
                'filename' => $request->file('main_filename')->getClientOriginalName()
            ]);
        }

        if ($request->file('images') && count($request->file('images')) > 0) {
            foreach ($request->file('images') as $key => $file) {
                $uploadedFile = $request->file('images.' . $key . '.filename');
                Storage::disk('uploads')->putFileAs('uploads/advertisements/' . $ad->id, $uploadedFile, $uploadedFile->getClientOriginalName());
                $ad->images()->create([
                    'filename' => $uploadedFile->getClientOriginalName(),
                    'main_filename' => false
                ]);
            }
        }

        $ad->categories()->sync($request->get('categories'));
        $ad->cities()->sync($request->get('cities'));

        return redirect()->route('advertisements.edit', ['advertisement' => $ad->id]);
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        try {
            $ad = Advertisement::findOrFail($id);
        } catch (ModelNotFoundException $exception) {
            return redirect()->route('advertisements.index')->withErrors($exception);
        }

        Storage::disk('uploads')->deleteDirectory('uploads/advertisements/' . $id);
        $ad->delete();

        return redirect()->route('advertisements.index');
    }

    /**
     * @param $request
     * @param bool $id
     * @return mixed
     */
    private function validateRequest($request, $id = false)
    {
        $mainFilename = $id ? 'file|mimes:jpeg,jpg,bmp,png,svg|max:10240' : 'required|file|mimes:jpeg,jpg,bmp,png,svg|max:10240';
        $validator = [
            'title' => 'required|string|max:150',
            'description' => 'string',
            'price' => 'required|numeric|min:0',
            'active' => 'required|boolean',
            'expires_at' => 'required|date|after:tomorrow',
            'main_filename' => $mainFilename,
            'categories' => 'array|required',
            'categories.*' => 'exists:categories,id',
            'cities' => 'array|required',
            'cities.*' => 'exists:cities,id',
            'images' => 'array',
            'images.*.filename' => 'file|mimes:jpeg,jpg,bmp,png,svg|max:10240'
        ];
        return $request->validate($validator);
    }

    /**
     * @param $ad
     * @param $image
     * @return \Illuminate\Http\JsonResponse
     */
    public function deleteImage($ad, $image)
    {
        try {
            $adFound = Advertisement::findOrFail($ad);
            $imageFound = AdvertisementImage::findOrFail($image);
        } catch (\Throwable $exception) {
            return response()->json([
                'error' => 'Не може да бъде намерена такава обява или снимка'
            ], 404);
        }

        Storage::disk('uploads')->delete('uploads/advertisements/' . $ad . '/' . $imageFound->filename);
        $imageFound->delete();

        return response()->json([
            'message' => 'success'
        ], 200);
    }
}

resources/views/admin/advertisements/index.blade.php
@extends('admin.layouts.admin')

@section('content')
    @if(Session::has('success_message'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ Session::get('success_message') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="row">
        <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Обяви</h4>
                    <div class="page-description d-flex mb-5">
                        <div class="col-12 col-md-12 text-right">
                            <a class="btn btn-success" href="{{route('advertisements.create')}}" title="Нова обява"><i
                                        class="icon-plus mr-2"></i>Нова обява</a>
                        </div>
                    </div>
                    <div id="order-listing_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-lg-12 table-responsive">
                                <table class="table dataTable table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Заглавие<i class="mdi mdi-chevron-down"></i></th>
                                        <th>Цена<i class="mdi mdi-chevron-down"></i></th>
                                        <th>Брой преглеждания<i class="mdi mdi-chevron-down"></i></th>
                                        <th>Създадена<i class="mdi mdi-chevron-down"></i></th>
                                        <th>Изтича на<i class="mdi mdi-chevron-down"></i></th>
                                        <th class="text-center">Промени</th>
                                        <th class="text-center">Изтрий</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse ($ads as $ad)
                                        <tr>
                                            <td>{{ $ad->title }}</td>
                                            <td>{{ $ad->price }} лв.</td>
                                            <td>{{ $ad->views_count }}</td>
                                            <td>{{ $ad->created_at->format('d M Y') }}</td>
                                            <td>{{ $ad->expires_at->format('d M Y') }}</td>
                                            <td class="jsgrid-cell jsgrid-control-field jsgrid-align-center text-center">
                                                <a class="edit-button btn btn-outline-primary"
                                                   href="{{route('advertisements.edit', ['advertisement' => $ad->id])}}"
                                                   title="Промени"><i class="icon-pencil menu-icon mr-0"></i></a>
                                            </td>
                                            <td class="jsgrid-cell jsgrid-control-field jsgrid-align-center text-center">
                                                <form method="POST"
                                                      action="{{route('advertisements.destroy', ['advertisement' => $ad->id])}}"
                                                      class="forms-sample">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit"
                                                            onclick="return confirm('Сигурни ли сте, че искате да изтриете тази обява?')"
                                                            class="delete-button btn btn-outline-danger" title="Изтрий"><i
                                                                class="icon-trash menu-icon mr-0"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7">Не са намерени обяви</td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection