routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

/****** ADMIN *******/

Route::prefix('igc-admin')->group(function () {
    Route::get('login', 'Admin\AuthController@showLoginForm')->name('admin.loginForm');
    Route::post('login', 'Admin\AuthController@login')->name('admin.login');
    Route::post('logout', 'Admin\AuthController@logout')->name('admin.logout');

    Route::group(['middleware' => 'admin.auth'], function() {
        Route::get('pages', 'Admin\PageController@index')->name('admin.pages.index');
        Route::get('pages/create', 'Admin\PageController@create')->name('admin.pages.create');
        Route::post('pages', 'Admin\PageController@store')->name('admin.pages.store');
        Route::get('pages/{id}', 'Admin\PageController@edit')->name('admin.pages.edit');
        Route::put('pages/{id}', 'Admin\PageController@update')->name('admin.pages.update');
        Route::delete('pages/{id}', 'Admin\PageController@destroy')->name('admin.pages.destroy');
        Route::resource('categories', 'Admin\CategoryController')->except(['show']);
        Route::resource('cities', 'Admin\CityController')->except(['show']);
        Route::resource('advertisements', 'Admin\AdvertisementController')->except(['show']);
        Route::delete('advertisements/{advertisement}/image/{image}', 'Admin\AdvertisementController@deleteImage');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/advertisements/{advertisement}', 'HomeController@show')->name('showAdvertisement');

resources/views/admin/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ 'IGC Admin Panel' }}</title>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- inject:css -->
    <link href="{{ asset('admin/css/admin.css') }}" rel="stylesheet">
</head>
<body>
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper">
            <a class="navbar-brand brand-logo" href="{{route('admin.pages.index')}}">
                <img src="{{ asset('images/igc-logo.jpg') }}" width="120" alt="IGC Logo"/>
            </a>
            <a class="navbar-brand brand-logo-mini" href="{{route('admin.pages.index')}}">
                <img src="{{ asset('images/igc-logo.jpg') }}" width="120" alt="IGC Logo"/>
            </a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center">
            <ul class="nav navbar-nav ml-lg-auto">
                <li class="nav-item dropdown d-none d-sm-block profile-img">
                    <a class="nav-link dropdown-toggle profile-image" href="#" role="button"
                       data-toggle="dropdown" aria-expanded="false">
                        <img src="{{asset('admin/images/faces-clipart/pic-4.png')}}" alt="profile-img" title="{{auth()->user()->name}}">
                        <span class="online-status online bg-success"></span>
                    </a>
                    <div class="dropdown-menu navbar-dropdown dropdown-menu-right">
                        <form action="{{route('admin.logout')}}" method="POST" class="dropdown-item">
                            @csrf
                            <button type="submit" class="dropdown-item">{{__('Изход')}}</button>
                        </form>
                    </div>
                </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center ml-auto" type="button"
                    data-toggle="offcanvas">
                <span class="icon-menu icons"></span>
            </button>
        </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <div class="row row-offcanvas row-offcanvas-right position-relative">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-category">
                        <span class="nav-link">СТРАНИЦИ</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('admin.pages.index')}}">
                            <span class="menu-title">Виж всички</span>
                            <i class="icon-notebook menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item nav-category">
                        <span class="nav-link">КАТЕГОРИИ</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('categories.index')}}">
                            <span class="menu-title">Виж всички</span>
                            <i class="icon-layers menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item nav-category">
                        <span class="nav-link">НАСЕЛЕНИ МЕСТА</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('cities.index')}}">
                            <span class="menu-title">Виж всички</span>
                            <i class="icon-home menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item nav-category">
                        <span class="nav-link">ОБЯВИ</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('advertisements.index')}}">
                            <span class="menu-title">Виж всички</span>
                            <i class="icon-list menu-icon"></i>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- partial -->
            <div class="content-wrapper">
                @yield('content')
            </div>
            <!-- content-wrapper ends -->
            <footer class="footer">
                <div class="container-fluid clearfix">
                    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © {{now()->year}}</span>
                </div>
            </footer>
            <!-- partial -->
        </div>
        <!-- row-offcanvas ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<script>
    window.base_path = '{{ env('APP_URL') }}';
</script>
<!-- container-scroller -->
<script src="{{ asset('admin/js/admin.js') }}"></script>
@yield('admin-js')
</body>

</html>

resources/views/admin/layouts/login.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ 'IGC Admin Panel' }}</title>

    <!-- Styles -->
    <link href="{{ asset('admin/css/admin.css') }}" rel="stylesheet">
    <style>
        body {
            height: 100vh;
            background-color: #f1f1f1;
        }

        .navbar {
            position: relative;
            min-height: 50px;
            margin-bottom: 22px;
            border: 1px solid transparent;
        }

        .navbar .container {
            padding-left: 15px;
            padding-right: 15px;
            margin: 0 auto;
        }

        .navbar-header {
            float: left;
        }

        .navbar-default .navbar-collapse, .navbar-default .navbar-form {
            border-color: #d3e0e9;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .navbar-nav > li {
            float: left;
        }

        .nav > li, .nav > li > a {
            display: block;
            position: relative;
        }

        .navbar-nav > li > a {
            padding-top: 14px;
            padding-bottom: 14px;
        }

        .navbar-collapse.collapse {
            display: block !important;
            height: auto !important;
            padding-bottom: 0;
            overflow: visible !important;
        }

        .navbar > .container, .navbar > .container-fluid {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: nowrap;
            flex-wrap: nowrap;
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            -webkit-box-pack: justify;
            -ms-flex-pack: justify;
            justify-content: space-between;
        }
    </style>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-laravel navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ route('admin.loginForm') }}">
                    <img src="{{ asset('images/igc-logo.jpg') }}" width="120" alt="IGC Logo"/>
                </a>
            </div>
        </div>
    </nav>

    @yield('content')
</div>
<!-- Scripts -->
<script src="{{ asset('admin/js/admin.js') }}"></script>
</body>
</html>