routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

/****** ADMIN *******/

Route::prefix('igc-admin')->group(function () {
    Route::get('login', 'Admin\AuthController@showLoginForm')->name('admin.loginForm');
    Route::post('login', 'Admin\AuthController@login')->name('admin.login');
    Route::post('logout', 'Admin\AuthController@logout')->name('admin.logout');

    Route::group(['middleware' => 'admin.auth'], function() {
        Route::get('pages', 'Admin\PageController@index')->name('admin.pages.index');
        Route::get('pages/create', 'Admin\PageController@create')->name('admin.pages.create');
        Route::post('pages', 'Admin\PageController@store')->name('admin.pages.store');
        Route::get('pages/{id}', 'Admin\PageController@edit')->name('admin.pages.edit');
        Route::put('pages/{id}', 'Admin\PageController@update')->name('admin.pages.update');
        Route::delete('pages/{id}', 'Admin\PageController@destroy')->name('admin.pages.destroy');
        Route::resource('categories', 'Admin\CategoryController')->except(['show']);
        Route::resource('cities', 'Admin\CityController')->except(['show']);
        Route::resource('advertisements', 'Admin\AdvertisementController')->except(['show']);
        Route::delete('advertisements/{advertisement}/image/{image}', 'Admin\AdvertisementController@deleteImage');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/advertisements/{advertisement}', 'HomeController@show')->name('showAdvertisement');

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title'
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function advertisements()
    {
        return $this->belongsToMany(Advertisement::class, 'advertisement_cities')->orderBy('id', 'DESC');
    }
}

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\City;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class CityController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $cities = City::orderBy('id', 'DESC')->get();
        return view('admin.cities.index', compact('cities'));
    }

    /**
     * Show the form for creating a new category.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cities.create');
    }

    /**
     * Store new category
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validateRequest($request);

        $city = City::create([
            'title' => $request->get('title')
        ]);

        return redirect()->route('cities.edit', ['city' => $city->id])->with('success_message', 'Успешно създадено населено място.');
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        try {
            $city = City::findOrFail($id);
        } catch (ModelNotFoundException $exception) {
            return redirect()->route('cities.index')->withErrors($exception);
        }

        return view('admin.cities.edit', compact('city'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            $city = City::findOrFail($id);
        } catch (ModelNotFoundException $exception) {
            return redirect()->route('cities.index')->withErrors($exception);
        }

        $this->validateRequest($request);

        $city->update([
            'title' => $request->get('title')
        ]);

        return redirect()->route('cities.edit', ['city' => $city->id])
            ->with('success_message', 'Успешно променено населено място.');
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        try {
            $city = City::findOrFail($id);
        } catch (ModelNotFoundException $exception) {
            return redirect()->route('cities.index')->withErrors($exception);
        }

        $city->delete();

        return redirect()->route('cities.index');
    }

    /**
     * @param $request
     * @return mixed
     */
    private function validateRequest($request)
    {
        $validator = [
            'title' => 'required|string|max:100'
        ];
        return $request->validate($validator);
    }
}

resources/views/admin/cities/create.blade.php
@extends('admin.layouts.admin')

@section('content')
    @if(Session::has('success_message'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ Session::get('success_message') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{__('Добави ново населено място')}}</h4>
                    <div class="row">
                        <div class="col-xl-12">
                            <form method="POST" action="{{route('cities.store')}}"
                                  class="forms-sample mt-4">
                                @csrf
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Име</label>
                                        <div class="col-sm-9">
                                            <input type="text"
                                                   class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}"
                                                   name="title" value="{{old('title')}}" required/>
                                            @error('title')
                                                <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-success mr-2 mt-3">Запази</button>
                                <a href="{{route('cities.index')}}" class="btn btn-light mt-3">Отмени</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/cities/edit.blade.php
@extends('admin.layouts.admin')

@section('content')
    @if(Session::has('success_message'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ Session::get('success_message') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{__('Редактирай населено място')}}</h4>
                    <div class="row">
                        <div class="col-xl-12">
                            <form method="POST" action="{{route('cities.update', ['city' => $city->id])}}"
                                  class="forms-sample mt-4">
                                @method('PUT')
                                @csrf
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Име</label>
                                        <div class="col-sm-9">
                                            <input type="text"
                                                   class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}"
                                                   name="title" value="{{ $city->title }}" required/>
                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-success mr-2 mt-3">Промени</button>
                                <a href="{{route('cities.index')}}" class="btn btn-light mt-3">Отмени</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/cities/index.blade.php
@extends('admin.layouts.admin')

@section('content')
    @if(Session::has('success_message'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ Session::get('success_message') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <div class="row">
        <div class="col-12 grid-margin">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Населени места</h4>
                    <div class="page-description d-flex mb-5">
                        <div class="col-12 col-md-12 text-right">
                            <a class="btn btn-success" href="{{route('cities.create')}}" title="Ново населено място"><i
                                        class="icon-plus mr-2"></i>Ново населено място</a>
                        </div>
                    </div>
                    <div id="order-listing_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
                        <div class="row">
                            <div class="col-lg-12 table-responsive">
                                <table class="table dataTable table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Име<i class="mdi mdi-chevron-down"></i></th>
                                        <th>Създадена<i class="mdi mdi-chevron-down"></i></th>
                                        <th class="text-center">Промени</th>
                                        <th class="text-center">Изтрий</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse ($cities as $city)
                                        <tr>
                                            <td>{{ $city->title }}</td>
                                            <td>{{ $city->created_at->format('d M Y') }}</td>
                                            <td class="jsgrid-cell jsgrid-control-field jsgrid-align-center text-center">
                                                <a class="edit-button btn btn-outline-primary"
                                                   href="{{route('cities.edit', ['city' => $city->id])}}"
                                                   title="Промени"><i class="icon-pencil menu-icon mr-0"></i></a>
                                            </td>
                                            <td class="jsgrid-cell jsgrid-control-field jsgrid-align-center text-center">
                                                <form method="POST"
                                                      action="{{route('cities.destroy', ['city' => $city->id])}}"
                                                      class="forms-sample">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit"
                                                            onclick="return confirm('Сигурни ли сте, че искате да изтриете това населено място?')"
                                                            class="delete-button btn btn-outline-danger" title="Изтрий"><i
                                                                class="icon-trash menu-icon mr-0"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7">Не са намерени населени места</td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection